package com.admarketplace.offheap;

import java.lang.reflect.Field;

import com.admarketplace.isg.util.Util;

import sun.misc.Unsafe;

public class OffString {

	private long address;
	public int sizeOffset = 8;
	private final int characterOffSET = 8;
	private int safety = 4;
	private int charByetSize=8;

	private static Unsafe theUnsafe;
	static {
		Field singleoneInstanceField;
		try {
			singleoneInstanceField = Unsafe.class.getDeclaredField("theUnsafe");
			singleoneInstanceField.setAccessible(true);
			theUnsafe = (Unsafe) singleoneInstanceField.get(null);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void printString(long i) {

		System.out.println(" getOffString : " + getOffString());
	}

	public long createOffString(String str) {

		char[] charArray = str.toCharArray();
		
		address = theUnsafe.allocateMemory(((charArray.length) * charByetSize) + safety);
		// System.out.println(" address : " + address);
		// System.out.println(" str.length() : " + str.length());

		theUnsafe.putInt(address, charArray.length);

		for (int i = 0; i <charArray.length; i++) {
			putChar(address + sizeOffset + (i * characterOffSET), charArray[i]);
		}
		return address;
	}

	public OffString() {
	}

	public String getOffString() {
		String str = "";
		int size = theUnsafe.getInt(address);
		System.out.println("size is " + size);
		for (int i = 0; i < size; i++) {
			char ch = theUnsafe.getChar(address + sizeOffset + (i * charByetSize));
			System.out.println("char is : " + ch);
			str += ch;

		}
		return str;
	}
public static int num = 100000;
	public static void main(String args[]) {
		Util.printProcessId();
//		runOnHeapTest();
		runOffHeapTest();
		
	}
 public static void runOffHeapTest()
 {
		// OffString str = new OffString();
		// str.putChar('a');
		// System.out.println(str.printChar());
		OffString str = new OffString();
		long startTime = System.currentTimeMillis();
		
//		Long[] addressesOfStrings = new Long[num];
		System.out.println("before offheap: Free memory (bytes): "
				+ Runtime.getRuntime().freeMemory());
		long startFreeMemory = Runtime.getRuntime().freeMemory();
		for (int i = 0; i < num; i++) {
//			addressesOfStrings[i] =
					str.createOffString(constStr);
		}
		
		long offsetTime = System.currentTimeMillis() - startTime;
		long endFreeMemory = Runtime.getRuntime().freeMemory();
		System.out.println("after offheap : Free memory (bytes): "
				+ endFreeMemory);
		System.out.println("offheap took " + (offsetTime) + " millis");
		System.out.println("offheap took bytes  "
				+ (startFreeMemory - endFreeMemory));

 }
	private static void runOnHeapTest() {
		long startTime = System.currentTimeMillis();
		long startFreeMemory = Runtime.getRuntime().freeMemory();
		System.out.println(" onheap start Free memory : "+startFreeMemory);
	
		for (long i = 0; i < num; i++) {

			String strObj = new String(constStr);

		}
		System.out.println("took " + (System.currentTimeMillis() - startTime)
				+ " millis");
		long endFreeMemory = Runtime.getRuntime().freeMemory();
		System.out.println(" onheap end Free memory : "+endFreeMemory);
		System.out.println("heap took bytes  "
				+ (startFreeMemory - endFreeMemory));

	}

	private char printChar() {
		// TODO Auto-generated method stub
		return theUnsafe.getChar(address);
	}

	private void putChar(long addressofchar, char character) {
		theUnsafe.putChar(addressofchar, character);

	}

	public static String constStr = "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassjcanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"+
			"hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan"
			+ "hassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassanhassan";


}
